### ISSUE TITLE
Error while getting pmem: go get github.com/vmware/go-pmem-transaction/pmem 

### ISSUE THREAD

**Issue by Muktikanta0123** [jerrinsg/go-pmem#23]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mukti/.cache/go-build"
GOENV="/home/mukti/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mukti/work/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mukti/work"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.16/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/mukti/go-ycsb/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1948807975=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
I wanted to import go-pmem/transaction/redis, to my project to use pnew(), pmake(), t_string, dictionary, etc.

### What did you expect to see?
go get should able to import.

### What did you see instead?
The errors:
go get github.com/vmware/go-pmem-transaction/pmem
"#github.com/vmware/go-pmem-transaction/transaction"
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/movnt.go:26:2: undefined: runtime.FlushRange
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/optEnd.go:73:3: undefined: runtime.Fence
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/optEnd.go:85:3: undefined: runtime.FlushRange
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:97:15: undefined: pnew
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:97:19: type redoTxHeader is not an expression
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:104:3: undefined: runtime.PersistRange
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:106:3: undefined: runtime.PersistRange
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:135:8: undefined: pnew
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:135:12: type redoTx is not an expression
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:137:11: undefined: pmake
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:137:11: too many errors

**Comment by mohit10verma** [comment]
Hi @Muktikanta0123 , Our repository github.com/vmware/go-pmem-transaction/ assumes you are using the go-pmem fork (https://github.com/vmware/go-pmem-transaction#readme) as your go binary. Say you compile this fork and the binary is at /tmp/go-pmem-fork/go, then this works:
/tmp/go-pmem-fork/go get github.com/vmware/go-pmem-transaction/pmem

**Comment by Muktikanta0123** [comment]
Thank you very much.
Then while importing we will add it like this?
import (
	"github.com/vmware/go-pmem-transaction/pmem"
	"github.com/vmware/go-pmem-transaction/transaction"
)

**Comment by mohit10verma** [comment]
Yes. These imports work. Remember to use the go-pmem fork (this repository) for building your applications.

**Comment by Muktikanta0123** [comment]
Yes, I already get transaction and pmem through  that fork and it is working fine. But while importing I am getting same error. 
Let me share the sequence of things I did. 

**(base) mukti@mukti:~/go-ycsb$ ~/go-pmem/bin/go get github.com/vmware/go-pmem-transaction/transaction**
go: found github.com/vmware/go-pmem-transaction/transaction in github.com/vmware/go-pmem-transaction v0.0.0-20210401173707-6e2b76e1a20d
**(base) mukti@mukti:~/go-ycsb$ ~/go-pmem/bin/go get github.com/vmware/go-pmem-transaction/pmem**
go: found github.com/vmware/go-pmem-transaction/pmem in github.com/vmware/go-pmem-transaction v0.0.0-20210401173707-6e2b76e1a20d
**(base) mukti@mukti:~/go-ycsb$ make**
go build -o bin/go-ycsb cmd/go-ycsb/*
"# github.com/vmware/go-pmem-transaction/transaction"
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/movnt.go:26:2: undefined: runtime.FlushRange
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/optEnd.go:73:3: undefined: runtime.Fence
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/optEnd.go:85:3: undefined: runtime.FlushRange
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:97:15: undefined: pnew
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:97:19: type redoTxHeader is not an expression
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:104:3: undefined: runtime.PersistRange
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:106:3: undefined: runtime.PersistRange
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:135:8: undefined: pnew
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:135:12: type redoTx is not an expression
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:137:11: undefined: pmake
../work/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/transaction/redoTx.go:137:11: too many errors
make: *** [Makefile:21: build] Error 2

**Comment by mohit10verma** [comment]
Your make command does not use the go-pmem binary . From the log above -- `go build -o bin/go-ycsb cmd/go-ycsb/*`

**Comment by Muktikanta0123** [comment]
Thank you, it is working but I am getting other bugs:
$make
~/go-pmem/bin/go build  -o bin/go-ycsb cmd/go-ycsb/*
"# github.com/dgraph-io/badger"
../work/pkg/mod/github.com/dgraph-io/badger@v1.5.4/backup.go:52:22: syntax error: unexpected txn, expecting )
../work/pkg/mod/github.com/dgraph-io/badger@v1.5.4/backup.go:55:9: syntax error: unexpected txn, expecting expression
../work/pkg/mod/github.com/dgraph-io/badger@v1.5.4/backup.go:83:11: syntax error: unexpected txn, expecting expression
../work/pkg/mod/github.com/dgraph-io/badger@v1.5.4/backup.go:84:3: syntax error: unexpected return at end of statement
"# github.com/coreos/etcd/clientv3"
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:71:2: syntax error: unexpected txn, expecting field name or embedded type
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:77:56: syntax error: unexpected txn, expecting name or (
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:79:39: syntax error: unexpected OpResponse at end of statement
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:89:20: syntax error: unexpected txn, expecting expression
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:137:10: syntax error: unexpected txn, expecting expression
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:142:1: syntax error: non-declaration statement outside function body
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:171:22: syntax error: unexpected txn, expecting expression
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:173:2: syntax error: unexpected default, expecting }
make: *** [Makefile:21: build] Error 2

Can you please tell how to fix these?
As I am using your go binary file to build. It is due to that, maybe I don't know

**Comment by jerrinsg** [comment]
You need to add the `-txn` flag while building your sources. Can you try changing your Makefile to do the following:
```
 ~/go-pmem/bin/go build -txn -o bin/go-ycsb cmd/go-ycsb/*
```

**Comment by Muktikanta0123** [comment]
I already tried that, but getting same errors.

**Comment by Muktikanta0123** [comment]
$ make
~/go-pmem/bin/go build -txn -o bin/go-ycsb cmd/go-ycsb/*
"# github.com/dgraph-io/badger"
../work/pkg/mod/github.com/dgraph-io/badger@v1.5.4/backup.go:52:22: syntax error: unexpected txn, expecting )
../work/pkg/mod/github.com/dgraph-io/badger@v1.5.4/backup.go:55:9: syntax error: unexpected txn, expecting expression
../work/pkg/mod/github.com/dgraph-io/badger@v1.5.4/backup.go:83:11: syntax error: unexpected txn, expecting expression
../work/pkg/mod/github.com/dgraph-io/badger@v1.5.4/backup.go:84:3: syntax error: unexpected return at end of statement
"# github.com/coreos/etcd/clientv3"
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:71:2: syntax error: unexpected txn, expecting field name or embedded type
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:77:56: syntax error: unexpected txn, expecting name or (
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:79:39: syntax error: unexpected OpResponse at end of statement
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:89:20: syntax error: unexpected txn, expecting expression
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:137:10: syntax error: unexpected txn, expecting expression
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:142:1: syntax error: non-declaration statement outside function body
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:171:22: syntax error: unexpected txn, expecting expression
../work/pkg/mod/github.com/coreos/etcd@v3.3.12+incompatible/clientv3/kv.go:173:2: syntax error: unexpected default, expecting }
make: *** [Makefile:21: build] Error 2

**Comment by jerrinsg** [comment]
Can you share your Makefile? Looks like the badger and etcd packages are getting compiled with a Go binary that is not go-pmem and hence you are getting these errors.

**Comment by Muktikanta0123** [comment]
Yes your are right, other packages are compiled with your binary file. I have emailed you the Makefile and shared the project in the google drive.
