### ISSUE TITLE
simple example.go could not find the go modules pmem and transactions.

### ISSUE THREAD

**Issue by yuwgit** [jerrinsg/go-pmem#27]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version devel +51612660da Thu Jan 21 18:58:07 2021 -0800 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

This problem is specific to the example.go program under go-pmem. I can run other go example programs well.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wkyu/.cache/go-build"
GOENV="/home/wkyu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/wkyu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/wkyu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/wkyu/research/gc/go-pmem"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/wkyu/research/gc/go-pmem/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build184554646=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Followed the README.md until the following steps.

wkyu@inv10:~/research/gc/go-pmem$ go get -u github.com/vmware/go-pmem-transaction/...                                                 
go: found github.com/vmware/go-pmem-transaction/... in github.com/vmware/go-pmem-transaction v0.0.0-20210401173707-6e2b76e1a20d
wkyu@inv10:~/research/gc/go-pmem$ cd design/
wkyu@inv10:~/research/gc/go-pmem/design$ GO111MODULE=off ../bin/go build -txn example.go
example.go:7:2: cannot find package "github.com/vmware/go-pmem-transaction/pmem" in any of:
        /home/wkyu/research/gc/go-pmem/src/github.com/vmware/go-pmem-transaction/pmem (from $GOROOT)
        /home/wkyu/go/src/github.com/vmware/go-pmem-transaction/pmem (from $GOPATH)
example.go:8:2: cannot find package "github.com/vmware/go-pmem-transaction/transaction" in any of:
        /home/wkyu/research/gc/go-pmem/src/github.com/vmware/go-pmem-transaction/transaction (from $GOROOT)
        /home/wkyu/go/src/github.com/vmware/go-pmem-transaction/transaction (from $GOPATH)

I only used the examle.go under the latest checkout from https://github.com/jerrinsg/go-pmem.git 

### What did you expect to see?

I expect the example.go to run smoothly.

### What did you see instead?

The code breaks with an error on not able to find pmem and transaction modules. They are both available under my default GOPATH as shown below.

wkyu@inv10:~/research/gc/go-pmem/design$ ls /home/wkyu/go/pkg/mod/github.com/vmware/go-pmem-transaction@v0.0.0-20210401173707-6e2b76e1a20d/
CONTRIBUTING.md  examples  LICENSE  NOTICE  pmem  pmemtest  README.md  transaction  txtest

**Comment by jerrinsg** [comment]
Hi,

Can you follow the steps mentioned in the following link and see if it helps - https://github.com/jerrinsg/go-pmem/issues/24#issuecomment-1194364771?

```
~$ go version
go version go1.18.3 linux/amd64

~$ git clone https://github.com/jerrinsg/go-pmem.git

~$ cd go-pmem/src

~/go-pmem/src$ ./make.bash

/go-pmem/src$ GO111MODULE=off ../bin/go get -u github.com/vmware/go-pmem-transaction/...

~/go-pmem/src$ cd ../design/

~/go-pmem/design$ GO111MODULE=off ../bin/go build -txn example.go

~/go-pmem/design$ ./example
First time initialization
Data set as  25  and  35

~/go-pmem/design$ ./example
Not a first time intialization
Read back data  25  and  35
```

**Comment by yuwgit** [comment]
Thanks a lot for your list of commands. I think the problem is with the go version I had. After I downgraded it from 1.19.1 to 1.18.3, everything worked well. (I put the message to a wrong thread).

$ git checkout go1.18.3
Previous HEAD position was 4a4127bccc [release-branch.go1.19] go1.19.1
HEAD is now at 4068be56ce [release-branch.go1.18] go1.18.3
